### ISSUE TITLE
Add url for collector system

### ISSUE THREAD

**Issue by frodelau** [SurveyAI/surveyai#49]
Currently only name, but adding website domain would be good
http://dev-env-2.eu-central-1.elasticbeanstalk.com/admin/app/collectorsystem/add/ :)

**Comment by hans-engstad** [comment]
Domain name is now an attribute on the Collector System model. This means that the domain could be added to the collector system, but not on a per survey level. 

If two surveys should use the same collector system, but use different domain names, I would suggest to create two seperate Collector Systems and give these appropriate names to be able to distiguish these from eachother. This approach assumes that a collector system normally will have the same domain name accross all users.

**Comment by frodelau** [comment]
Sounds as a good apprach. Surveymonkey has research.net in addition to surveymonkey.com. But most cases is one collector = one domain :)
