### ISSUE TITLE
Make the population separate from respondent type

### ISSUE THREAD

**Issue by frodelau** [SurveyAI/surveyai#50]
Should be a separate setting in the survey, independent of respondent type
<img width="630" alt="skjermbilde 2019-02-15 kl 13 52 31" src="https://user-images.githubusercontent.com/546803/52857985-2c68da00-3129-11e9-8759-4b25bd4c80cf.png">

**Comment by hans-engstad** [comment]
Population real and Population sampling are now attributes belonging to a survey.

**Comment by frodelau** [comment]
Very good :)
