### ISSUE TITLE
Add "Consultancy" as separate setting for survey

### ISSUE THREAD

**Issue by frodelau** [SurveyAI/surveyai#51]
As many companies/brands are using 3rd party companies (consultancies) to do data collection and reporting on their behalf, it would be greate to get an overview of these.

**Comment by hans-engstad** [comment]
Should it be possible to add data about what consultancy company was used, or is it enough to know that a survey has been created by a concultancy company?

**Comment by frodelau** [comment]
Would be best to be able to set name of consultancy. We1ll see how much it is used. But it is a good list of potential customers this :)

**Comment by hans-engstad** [comment]
Added consultancy as text field on survey
