### ISSUE TITLE
Cannot create scale

### ISSUE THREAD

**Issue by frodelau** [SurveyAI/surveyai#52]
Clicking "new scale" - nothing happens. Error is shown in console 
/api/scale:1 Failed to load resource: the server responded with a status of 500 (Internal Server Error)
all:254 

<img width="1177" alt="skjermbilde 2019-03-07 kl 21 45 28" src="https://user-images.githubusercontent.com/546803/53987838-64f54580-4122-11e9-989f-b168da96885b.png">

**Comment by hans-engstad** [comment]
bug is fixed, new version deployed to Beanstalk.
